project:
  type: book

book:
  title: "Models"
  author: 
    - name: Michael Clark
      affiliations:
        - id: str
          name: Strong Analytics
    - name: Seth Berry
      affiliations:
        - id: ND
          name: University of Notre Dame
  # date: "2/17/2023"
  chapters:
    - index.qmd
    - 00-author.qmd
    - 01-introduction.qmd
    - 02-foo.qmd
#    - intro.qmd
#    - summary.qmd
#    - references.qmd



format:
  html:
    theme: 
    - materia # https://bootswatch.com/
    - mfs.scss
    mainfont: Roboto
    monofont: Roboto Mono
    fontsize: 1rem
    linkcolor: '#3958C4'
    code-block-bg: '#FAFAFA80'
    # table of contents
    toc: true
    toc-title: Contents
    toc-location: right
    toc-depth: 3
  pdf:
    documentclass: krantz
    pdf-engine: pdflatex
    # include-in-header: 
    #   text: |
    #     \usepackage{makeidx}
    #     \makeindex
    # include-after-body: 
    #   text: |
    #     \printindex
    toc: true
    keep-tex: true 
    lot: true
    lof: true
    graphics: yes
    hyperrefoptions: 
      - linktoc=none



# bibliography
# bibliography: refs.bib
biblio-style: chicago

# editing etc.
editor: source
engine: knitr
# jupyter: bom
execute:
  freeze  : true
  echo    : true 
  eval    : true
  message : false
  warning : false

knitr:
  opts_chunk: 
    message       : false 
    R.options     : list(width = 120)
    cache         : false
    cache.rebuild : false
    cache.lazy    : false
    fig.align     : 'center'
    fig.asp       : .7
    # dev       : 'svg'