project:
  type: book

book:
  title: "Models"
  subtitle: "A Practical Guide from t-tests to Deep Learning"
  # multiple author format will not work for pdf
  author: 
    - name: Michael Clark & Seth Berry
  chapters:
    - index.qmd
    - introduction.qmd  
    - part: "Linear Models"
      chapters:
        - linear_models.qmd
        - model_criticism.qmd
        - steps.qmd
        - estimation.qmd
        # - generalized_linear_models.qmd
        # - linear_model_extensions.qmd
    - part: "Machine Learning"
      chapters:
        - machine_learning.qmd
        - ml_common_models.qmd
        - ml_more.qmd
    - part: "Other Considerations"
      chapters:
        - data.qmd
  appendices:
      - references.qmd
      - dataset_descriptions.qmd
      - matrix_operations.qmd
      - appendix_placeholder.qmd
  search: true
  repo-url: https://github.com/m-clark/book-of-models
  repo-actions: [edit]
  downloads: [pdf]
  sharing: [twitter, linkedin]

format:
  html:
    theme: 
    - materia # https://bootswatch.com/
    - mfs.scss
    - css/style.scss
    mainfont: Roboto
    monofont: 'Roboto Mono'
    fontsize: 1rem
    linkcolor: '#3958C4'
    highlight-style: arrow
    code-block-bg: '#FAFAFA80'
    # table of contents
    toc: true
    toc-title: Contents
    toc-location: left
    toc-depth: 3
    mermaid: 
      theme: neutral
  pdf:
    documentclass: krantz
  #  pdf-engine: pdflatex
    toc: true
    toc-title: Contents
    toc-depth: 3
    keep-tex: true
    links-as-notes: true
    # highlight-style: none
    code-block-bg: '#FAFAFA'
    highlight-style: pygments
    colorlinks: true
    hyperrefoptions:
      - linktoc=none
    monofont: "Roboto Mono"
    monofontoptions: "Scale=0.7"
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex

    # not needed?
    # lof: true  # list of figures
    # lot: true  # list of tables
    # graphics: yes



# bibliography
bibliography: references.bib
biblio-style: chicago

# editing etc.
editor: source
# engine: jupyter
# jupyter: book-of-models

execute:
  freeze  : auto # not until some part is mostly ready 
  echo    : true 
  eval    : true
  message : false
  warning : false
tbl-cap-location: top
crossref:
  fig-prefix: Figure # can we do better than figure? 
  tbl-prefix: Table 
# knitr:
#   opts_chunk: 
#     message       : false 
#     R.options     : list(width = 120)
#     cache         : false
#     cache.rebuild : false
#     cache.lazy    : false
#     fig.align     : 'center'
#     fig.asp       : .7
    
    # dev       : 'svg'
