project:
  type: book

book:
  title: "Models"
  # this multiple author format will not work for pdf
  author: 
    - name: Michael Clark & Seth Berry
      # affiliations:
      #   - id: str
      #     name: Strong Analytics
    # - name: Seth Berry
    #   affiliations:
    #     - id: ND
    #       name: University of Notre Dame
  # date: "2/17/2023"
  chapters:
    - index.qmd
    - introduction.qmd
  appendices:
    - references.qmd
  search: true
  repo-url: https://github.com/m-clark/book-of-models
  repo-actions: [edit]
  downloads: [pdf]
  sharing: [twitter, linkedin]

format:
  # html:
    # theme:
    # - materia # https://bootswatch.com/
    # - mfs.scss
    # mainfont: Roboto
    # monofont: Roboto Mono
    # fontsize: 1rem
    # linkcolor: '#3958C4'
    # code-block-bg: '#FAFAFA80'
    # # table of contents
    # toc: true
    # toc-title: Contents
    # toc-location: left
    # toc-depth: 3
  html:
    theme: 
    - materia # https://bootswatch.com/
    - mfs.scss
    - css/style.scss
    mainfont: Roboto
    monofont: 'Roboto Mono'
    fontsize: 1rem
    linkcolor: '#3958C4'
    code-block-bg: '#FAFAFA80'
    # table of contents
    toc: true
    toc-title: Contents
    toc-location: left
    toc-depth: 3
    mermaid: 
      theme: neutral
  pdf:
    documentclass: krantz
  #  pdf-engine: pdflatex
    toc: true
    toc-title: 'Contents'
    keep-tex: true
    links-as-notes: true
    highlight-style: none
    colorlinks: false
    hyperrefoptions:
      - linktoc=none
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex

    # not needed?

    # lof: true
    # lot: true
    # graphics: yes



# bibliography
bibliography: references.bib
biblio-style: chicago

# editing etc.
editor: source
# engine: jupyter
# jupyter: book-of-models

execute:
  freeze  : false # not until some part is mostly ready 
  echo    : true 
  eval    : true
  message : false
  warning : false
tbl-cap-location: top
crossref:
  fig-prefix: Figure # can we do better than figure? 
  tbl-prefix: Table 
# knitr:
#   opts_chunk: 
#     message       : false 
#     R.options     : list(width = 120)
#     cache         : false
#     cache.rebuild : false
#     cache.lazy    : false
#     fig.align     : 'center'
#     fig.asp       : .7
    
    # dev       : 'svg'
