project:
  type: book

book:
  title: "Models"
  # this multiple author format will not work for pdf
  author: 
    - name: Michael Clark & Seth Berry
      # affiliations:
      #   - id: str
      #     name: Strong Analytics
    # - name: Seth Berry
    #   affiliations:
    #     - id: ND
    #       name: University of Notre Dame
  # date: "2/17/2023"
  chapters:
    - index.qmd
    - introduction.qmd
#    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
    - materia # https://bootswatch.com/
    - mfs.scss
    mainfont: Roboto
    monofont: Roboto Mono
    fontsize: 1rem
    linkcolor: '#3958C4'
    code-block-bg: '#FAFAFA80'
    # table of contents
    toc: true
    toc-title: Contents
    # toc-location: left
    toc-depth: 3
  pdf:
    documentclass: krantz
    # pdf-engine: pdflatex
    # toc: true
    # toc-title: 'Contents'
    # keep-tex: true 
    # links-as-notes: true
    # highlight-style: none
    # colorlinks: false
    # lof: true
    # include-in-header:
    #   text: |
    #     \usepackage{makeidx}
    #     \makeindex
    # include-after-body:
    #   text: |
    #     \printindex

    # hyperrefoptions: 
    #   - linktoc=none
    # not needed?
    # lot: true
    # graphics: yes



# bibliography
# bibliography: refs.bib
biblio-style: chicago

# editing etc.
editor: source
# engine: jupyter
# jupyter: book-of-models

execute:
  # freeze  : true # not until some part is mostly ready 
  echo    : true 
  eval    : true
  message : false
  warning : false
tbl-cap-location: top
crossref:
  fig-prefix: Figure # can we do better than figure? 
  tbl-prefix: Table 
# knitr:
#   opts_chunk: 
#     message       : false 
#     R.options     : list(width = 120)
#     cache         : false
#     cache.rebuild : false
#     cache.lazy    : false
#     fig.align     : 'center'
#     fig.asp       : .7
    
    # dev       : 'svg'
